package intent

// Code generated - This file has been automatically generated by _dev/main.go - DO NOT EDIT.

func All() []Type {
	return []Type{
		DirectMessages,
		DirectMessageReactions,
		DirectMessageTyping,
		Guilds,
		GuildBans,
		GuildEmojisAndStickers,
		GuildIntegrations,
		GuildInvites,
		GuildMembers,
		GuildMessages,
		GuildMessageReactions,
		GuildMessageTyping,
		GuildPresences,
		GuildScheduledEvents,
		GuildVoiceStates,
		GuildWebhooks,
	}
}
