package event

// Code generated - This file has been automatically generated by internal/generate/events/main.go - DO NOT EDIT.

import (
	"github.com/discordpkg/gateway/event/opcode"
)

func (t Type) OpCode() opcode.Type {
	switch t {
	case Resume:
		return opcode.Resume
	case Heartbeat:
		return opcode.Heartbeat
	case VoiceStateUpdate:
		return opcode.VoiceStateUpdate
	case Hello:
		return opcode.Hello
	case Identify:
		return opcode.Identify
	case InvalidSession:
		return opcode.InvalidSession
	case PresenceUpdate:
		return opcode.PresenceUpdate
	case Reconnect:
		return opcode.Reconnect
	case RequestGuildMembers:
		return opcode.RequestGuildMembers
	default:
		return opcode.Dispatch
	}
}
