package event

// Code generated - This file has been automatically generated by internal/generate/events/main.go - DO NOT EDIT.
// Warning: This file is overwritten at "go generate", instead adapt internal/constants/events.go and run go generate

type Type string

// list off all 52 discord events
const (
	// ApplicationCommandCreate new Slash Command was created
	ApplicationCommandCreate Type = "APPLICATION_COMMAND_CREATE"

	// ApplicationCommandDelete Slash Command was deleted
	ApplicationCommandDelete Type = "APPLICATION_COMMAND_DELETE"

	// ApplicationCommandUpdate Slash Command was updated
	ApplicationCommandUpdate Type = "APPLICATION_COMMAND_UPDATE"

	// ChannelCreate new guild channel created
	ChannelCreate Type = "CHANNEL_CREATE"

	// ChannelDelete channel was deleted
	ChannelDelete Type = "CHANNEL_DELETE"

	// ChannelPinsUpdate Sent when a message is pinned or unpinned in a text channel. This is not sent when a pinned message is deleted.
	ChannelPinsUpdate Type = "CHANNEL_PINS_UPDATE"

	// ChannelUpdate channel was updated
	ChannelUpdate Type = "CHANNEL_UPDATE"

	// GuildBanCreate user was banned from a guild
	GuildBanCreate Type = "GUILD_BAN_ADD"

	// GuildBanDelete user was unbanned from a guild
	GuildBanDelete Type = "GUILD_BAN_REMOVE"

	// GuildCreate lazy-load for unavailable guild, guild became available, or user joined a new guild
	GuildCreate Type = "GUILD_CREATE"

	// GuildDelete guild became unavailable, or user left/was removed from a guild
	GuildDelete Type = "GUILD_DELETE"

	// GuildEmojisUpdate guild emojis were updated
	GuildEmojisUpdate Type = "GUILD_EMOJIS_UPDATE"

	// GuildIntegrationsUpdate Sent when a guild integration is updated.
	GuildIntegrationsUpdate Type = "GUILD_INTEGRATIONS_UPDATE"

	// GuildMemberCreate Sent when a new user joins a guild. The inner payload is a guild member object with these extra fields:
	GuildMemberCreate Type = "GUILD_MEMBER_ADD"

	// GuildMemberDelete Sent when a user is removed from a guild (leave/kick/ban).
	GuildMemberDelete Type = "GUILD_MEMBER_REMOVE"

	// GuildMemberUpdate Sent when a guild member is updated.
	GuildMemberUpdate Type = "GUILD_MEMBER_UPDATE"

	// GuildMembersChunk Sent in response to Gateway Request Guild Members.
	GuildMembersChunk Type = "GUILD_MEMBERS_CHUNK"

	// GuildRoleCreate Sent when a guild role is created.
	GuildRoleCreate Type = "GUILD_ROLE_CREATE"

	// GuildRoleDelete Sent when a guild role is created.
	GuildRoleDelete Type = "GUILD_ROLE_DELETE"

	// GuildRoleUpdate Sent when a guild role is created.
	GuildRoleUpdate Type = "GUILD_ROLE_UPDATE"

	// GuildUpdate guild was updated
	GuildUpdate Type = "GUILD_UPDATE"

	// Hello defines the heartbeat interval
	Hello Type = "HELLO"

	// IntegrationCreate guild integration was created
	IntegrationCreate Type = "INTEGRATION_CREATE"

	// IntegrationDelete guild integration was deleted
	IntegrationDelete Type = "INTEGRATION_DELETE"

	// IntegrationUpdate guild integration was updated
	IntegrationUpdate Type = "INTEGRATION_UPDATE"

	// InteractionCreate user used an interaction, such as a Slash Command
	InteractionCreate Type = "INTERACTION_CREATE"

	// InvalidSession failure response to Identify or Resume or invalid active session
	InvalidSession Type = "INVALID_SESSION"

	// InviteCreate	invite to a channel was created
	InviteCreate Type = "INVITE_CREATE"

	// InviteDelete	invite to a channel was deleted
	InviteDelete Type = "INVITE_DELETE"

	// MessageCreate message was created
	MessageCreate Type = "MESSAGE_CREATE"

	// MessageDelete message was deleted
	MessageDelete Type = "MESSAGE_DELETE"

	// MessageDeleteBulk multiple messages were deleted at once
	MessageDeleteBulk Type = "MESSAGE_DELETE_BULK"

	// MessageReactionCreate user reacted to a message
	MessageReactionCreate Type = "MESSAGE_REACTION_ADD"

	// MessageReactionDelete user removed a reaction from a message
	MessageReactionDelete Type = "MESSAGE_REACTION_REMOVE"

	// MessageReactionDeleteAll all reactions were explicitly removed from a message
	MessageReactionDeleteAll Type = "MESSAGE_REACTION_REMOVE_ALL"

	// MessageReactionDeleteEmoji all reactions for a given emoji were explicitly removed from a message
	MessageReactionDeleteEmoji Type = "MESSAGE_REACTION_REMOVE_EMOJI"

	// MessageUpdate message was edited
	MessageUpdate Type = "MESSAGE_UPDATE"

	// PresenceUpdate user was updated
	PresenceUpdate Type = "PRESENCE_UPDATE"

	// Ready contains the initial state information
	Ready Type = "READY"

	// Reconnect server is going away, client should reconnect to gateway and resume
	Reconnect Type = "RECONNECT"

	// Resumed response to Resume
	Resumed Type = "RESUMED"

	// ThreadCreate thread created, also sent when being added to a private thread
	ThreadCreate Type = "THREAD_CREATE"

	// ThreadDelete thread was deleted
	ThreadDelete Type = "THREAD_DELETE"

	// ThreadListSync sent when gaining access to a channel, contains all active threads in that channel
	ThreadListSync Type = "THREAD_LIST_SYNC"

	// ThreadMemberUpdate thread member for the current user was updated
	ThreadMemberUpdate Type = "THREAD_MEMBER_UPDATE"

	// ThreadMembersUpdate some user(s) were added to or removed from a thread
	ThreadMembersUpdate Type = "THREAD_MEMBERS_UPDATE"

	// ThreadUpdate thread was updated
	ThreadUpdate Type = "THREAD_UPDATE"

	// TypingStart user started typing in a channel
	TypingStart Type = "TYPING_START"

	// UserUpdate properties about the user changed
	UserUpdate Type = "USER_UPDATE"

	// VoiceServerUpdate guild's voice server was updated
	VoiceServerUpdate Type = "VOICE_SERVER_UPDATE"

	// VoiceStateUpdate someone joined, left, or moved a voice channel
	VoiceStateUpdate Type = "VOICE_STATE_UPDATE"

	// WebhooksUpdate guild channel webhook was created, update, or deleted
	WebhooksUpdate Type = "WEBHOOKS_UPDATE"
)

func All() []Type {
	return []Type{ApplicationCommandCreate, ApplicationCommandDelete, ApplicationCommandUpdate, ChannelCreate, ChannelDelete, ChannelPinsUpdate, ChannelUpdate, GuildBanCreate, GuildBanDelete, GuildCreate, GuildDelete, GuildEmojisUpdate, GuildIntegrationsUpdate, GuildMemberCreate, GuildMemberDelete, GuildMemberUpdate, GuildMembersChunk, GuildRoleCreate, GuildRoleDelete, GuildRoleUpdate, GuildUpdate, Hello, IntegrationCreate, IntegrationDelete, IntegrationUpdate, InteractionCreate, InvalidSession, InviteCreate, InviteDelete, MessageCreate, MessageDelete, MessageDeleteBulk, MessageReactionCreate, MessageReactionDelete, MessageReactionDeleteAll, MessageReactionDeleteEmoji, MessageUpdate, PresenceUpdate, Ready, Reconnect, Resumed, ThreadCreate, ThreadDelete, ThreadListSync, ThreadMemberUpdate, ThreadMembersUpdate, ThreadUpdate, TypingStart, UserUpdate, VoiceServerUpdate, VoiceStateUpdate, WebhooksUpdate}
}
