package event

// Code generated - This file has been automatically generated by internal/generate/events/main.go - DO NOT EDIT.

const (
	Heartbeat           Type = "HEARTBEAT"
	Identify            Type = "IDENTIFY"
	RequestGuildMembers Type = "REQUEST_GUILD_MEMBERS"
	Resume              Type = "RESUME"
	UpdatePresence      Type = "UPDATE_PRESENCE"
	UpdateVoiceState    Type = "UPDATE_VOICE_STATE"
)
