package closecode

// Code generated - This file has been automatically generated by internal/generate/closecode/main.go - DO NOT EDIT.

type Type uint32

// custom codes
const (
	HeartbeatAckNotReceived Type = 3000
	ClientReconnecting      Type = 1001
)

const (
	AlreadyAuthenticated Type = 4005
	AuthenticationFailed Type = 4004
	DecodeError          Type = 4002
	DisallowedIntents    Type = 4014
	InvalidAPIVersion    Type = 4012
	InvalidIntents       Type = 4013
	InvalidSeq           Type = 4007
	InvalidShard         Type = 4010
	NotAuthenticated     Type = 4003
	RateLimited          Type = 4008
	SessionTimedOut      Type = 4009
	ShardingRequired     Type = 4011
	UnknownError         Type = 4000
	UnknownOpcode        Type = 4001
)

func CanReconnectAfter(code Type) bool {
	_, reconnectCloseCode := map[Type]bool{
		AlreadyAuthenticated: true,
		DecodeError:          true,
		InvalidSeq:           true,
		NotAuthenticated:     true,
		RateLimited:          true,
		SessionTimedOut:      true,
		UnknownError:         true,
		UnknownOpcode:        true,
	}[code]

	return reconnectCloseCode
}
