package command

// Code generated - This file has been automatically generated by _dev/main.go - DO NOT EDIT.

type Type int

const (
	// Heartbeat maintains an active gateway connection
	Heartbeat Type = 1
	// Identify triggers the initial handshake with the gateway
	Identify Type = 2
	// RequestGuildMembers requests members for a guild
	RequestGuildMembers Type = 8
	// Resume resumes a dropped gateway connection
	Resume Type = 6
	// UpdatePresence updates a client's presence
	UpdatePresence Type = 3
	// UpdateVoiceState joins, moves, or disconnects the client from a voice channel
	UpdateVoiceState Type = 4
)

// Returns all 6 discord gateway commands
func All() []Type {
	return []Type{
		Heartbeat,
		Identify,
		RequestGuildMembers,
		Resume,
		UpdatePresence,
		UpdateVoiceState,
	}
}
