package opcode

// Code generated - This file has been automatically generated by internal/generate/events/main.go - DO NOT EDIT.

// Type is the discord operation value
type Type uint

const (
	Invalid Type = 0b111111111111 // 4095
)

// send / receive
const (
	Dispatch            Type = 0
	Heartbeat           Type = 1
	HeartbeatACK        Type = 11
	Hello               Type = 10
	Identify            Type = 2
	InvalidSession      Type = 9
	PresenceUpdate      Type = 3
	Reconnect           Type = 7
	RequestGuildMembers Type = 8
	Resume              Type = 6
	VoiceStateUpdate    Type = 4
)
