package opcode

// Code generated - This file has been automatically generated by internal/generate/opcode/main.go - DO NOT EDIT.

// Type is the discord operation value
type Type uint

const (
	Invalid Type = 0b111111111111 // 4095
)

// send / receive
const (
	Heartbeat Type = 1
)

// send only
const (
	Identify            Type = 2
	PresenceUpdate      Type = 3
	RequestGuildMembers Type = 8
	Resume              Type = 6
	VoiceStateUpdate    Type = 4
)

// receive only
const (
	Dispatch       Type = 0
	HeartbeatACK   Type = 11
	Hello          Type = 10
	InvalidSession Type = 9
	Reconnect      Type = 7
)
