on:
  pull_request:
    types:
      - synchronize
      - opened
      - reopened
  push:
    branches:
      - main

name: tests
jobs:
  unit-tests:
    name: unit tests & code coverage
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        go: ['1.18']
    steps:
      - name: Setup Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}
        id: go
      - name: Check out code
        uses: actions/checkout@master
      - name: Get dependencies
        run: go mod download
      - name: Format Test
        run: diff <(gofmt -d ./...) <(echo -n)
      - name: unit tests
        run: go test -short -v -race -shuffle=on -coverprofile=coverage.txt -covermode=atomic ./...
      - name: Codecov
        run: bash <(curl -s https://codecov.io/bash) -t ${{secrets.CODECOV_TOKEN}} -B master -c -F unit -f "./coverage.txt" -Z

